version: '3.5'
services:
  caddy:
    image: psucoder/caddy:no-stats
    restart: always
    environment:
      ACME_AGREE: "true"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
      - 443:443

  web:
    image: psucoder/sheets-web:v20200710-49149d4
    restart: always

  api:
    image: psucoder/sheets-api:v20200630-60e582d
    env_file:
      - .env
    restart: on-failure

  bot:
    image: psucoder/sheets-bot:v20200819-f73f387
    env_file:
      - .env
    restart: on-failure

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
