// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/noti.proto

package sheet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotifyTransactionRequest struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transactionId" json:"transactionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyTransactionRequest) Reset()         { *m = NotifyTransactionRequest{} }
func (m *NotifyTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyTransactionRequest) ProtoMessage()    {}
func (*NotifyTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noti_6048622ca4bdb837, []int{0}
}
func (m *NotifyTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyTransactionRequest.Unmarshal(m, b)
}
func (m *NotifyTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *NotifyTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyTransactionRequest.Merge(dst, src)
}
func (m *NotifyTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyTransactionRequest.Size(m)
}
func (m *NotifyTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyTransactionRequest proto.InternalMessageInfo

func (m *NotifyTransactionRequest) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type NotifyTransactionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyTransactionResponse) Reset()         { *m = NotifyTransactionResponse{} }
func (m *NotifyTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyTransactionResponse) ProtoMessage()    {}
func (*NotifyTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noti_6048622ca4bdb837, []int{1}
}
func (m *NotifyTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyTransactionResponse.Unmarshal(m, b)
}
func (m *NotifyTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *NotifyTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyTransactionResponse.Merge(dst, src)
}
func (m *NotifyTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyTransactionResponse.Size(m)
}
func (m *NotifyTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyTransactionResponse proto.InternalMessageInfo

func (m *NotifyTransactionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NotifyTransactionResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func init() {
	proto.RegisterType((*NotifyTransactionRequest)(nil), "sheet.NotifyTransactionRequest")
	proto.RegisterType((*NotifyTransactionResponse)(nil), "sheet.NotifyTransactionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationServiceClient interface {
	NotifyTransaction(ctx context.Context, in *NotifyTransactionRequest, opts ...grpc.CallOption) (*NotifyTransactionResponse, error)
}

type notificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationServiceClient(cc *grpc.ClientConn) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) NotifyTransaction(ctx context.Context, in *NotifyTransactionRequest, opts ...grpc.CallOption) (*NotifyTransactionResponse, error) {
	out := new(NotifyTransactionResponse)
	err := c.cc.Invoke(ctx, "/sheet.NotificationService/NotifyTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	NotifyTransaction(context.Context, *NotifyTransactionRequest) (*NotifyTransactionResponse, error)
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_NotifyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheet.NotificationService/NotifyTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyTransaction(ctx, req.(*NotifyTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sheet.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyTransaction",
			Handler:    _NotificationService_NotifyTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/noti.proto",
}

func init() { proto.RegisterFile("proto/noti.proto", fileDescriptor_noti_6048622ca4bdb837) }

var fileDescriptor_noti_6048622ca4bdb837 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcb, 0x2f, 0xc9, 0xd4, 0x03, 0x33, 0x85, 0x58, 0x8b, 0x33, 0x52, 0x53, 0x4b,
	0x94, 0x1c, 0xb8, 0x24, 0xfc, 0xf2, 0x4b, 0x32, 0xd3, 0x2a, 0x43, 0x8a, 0x12, 0xf3, 0x8a, 0x13,
	0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x54, 0xb8, 0x78,
	0x4b, 0x10, 0xa2, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xa8, 0x82, 0x4a, 0x21,
	0x5c, 0x92, 0x58, 0x4c, 0x28, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe0, 0x62, 0x2f, 0x2e,
	0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0x06, 0x6b, 0xe6, 0x08, 0x82, 0x71, 0x85, 0x64, 0xb9, 0xb8, 0x52,
	0x8b, 0x8a, 0xf2, 0x8b, 0xe2, 0x93, 0xf3, 0x53, 0x52, 0x25, 0x98, 0xc0, 0x26, 0x73, 0x82, 0x45,
	0x9c, 0xf3, 0x53, 0x52, 0x8d, 0x72, 0xb9, 0x84, 0xc1, 0xa6, 0x66, 0x26, 0x27, 0x82, 0x0c, 0x0c,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x0a, 0xe3, 0x12, 0xc4, 0xb0, 0x4c, 0x48, 0x5e, 0x0f,
	0xec, 0x17, 0x3d, 0x5c, 0x1e, 0x91, 0x52, 0xc0, 0xad, 0x00, 0xe2, 0xce, 0x24, 0x36, 0x70, 0xa0,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xbc, 0x07, 0xa4, 0x28, 0x01, 0x00, 0x00,
}
