// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	AuthIdentities      string
	Checkins            string
	FlywaySchemaHistory string
	TelegramTokens      string
	TransactionLogs     string
	Transactions        string
	Users               string
}{
	AuthIdentities:      "auth_identities",
	Checkins:            "checkins",
	FlywaySchemaHistory: "flyway_schema_history",
	TelegramTokens:      "telegram_tokens",
	TransactionLogs:     "transaction_logs",
	Transactions:        "transactions",
	Users:               "users",
}
