name: reviewdog
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: '-E goimports,revive api'
          go_version: 1.16
          filter_mode: file
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          workdir: ./web
          eslint_flags: '--ext vue,js,ts src'
          filter_mode: file
